name: valeayala
favicon: null
layout_spectrum: 0.93914
typography_spectrum: 0.48353
title: valanonima
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f2f7'
    - '#3a3a3c'
    - '#fdab4d'
    - '#24d3ea'
    - '#f9624a'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
