name: valeayala
favicon: null
layout_spectrum: 0.93914
typography_spectrum: 0.48353
title: valanonima
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cfb9a5'
    - '#81968f'
    - '#e8ccbf'
    - '#96bdc6'
    - '#e9d6ec'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
